Created a very generic read block that pulls all data from firebase
nio-blocks/firebase pull request #6
Opened 2017-06-08 20:54 UTC by tlugger

To create this I refactored the insert block to do a get request rather than put. It will return everything in the specified firebase collection as one signal. This does not yet have functionality to notify on database changes.

2017-06-08 21:11 UTC, hansmosh requested changes

2017-06-08 21:11 UTC, hansmosh commented on firebase_read_block.py
> +                self.logger.exception("Couldn't save signal")
Copy pasta

2017-06-08 21:11 UTC, hansmosh commented on firebase_read_block.py
> +            # so we need to compute it inside the loop
This is definitely just my opinion, but this comment (and the one about enriching this signal) seem unnecessary. I don't like comments that just explain in english what the next line of code is doing, especially if that line of code isn't particularly confusing.

2017-06-08 21:11 UTC, hansmosh commented on firebase_read_block.py
> +class FirebaseRead(FirebaseBase):
Lets get a unit test for this block.

2017-06-08 23:24 UTC, tlugger commented on firebase_read_block.py
> +                self.logger.exception("Couldn't save signal")
I'll fix the exception message to be more specific to the get request

2017-06-08 23:25 UTC, tlugger commented on firebase_read_block.py
> +            # so we need to compute it inside the loop
I agree that the comment blocks aren't necessary. These were copied over from the insert block as it had very similar functionality. I'll remove them from this block but would you recommend that I take them out of the insert block as well?

2017-06-09 16:07 UTC, hansmosh approved these changes

2017-06-09 16:10 UTC, merged